---
swagger: 2.0
info:
  description: Che Feature API
  version: 1.0.0
  title: Che Feature API
  contact:
    email: skabashniuk@redhat.com
  license:
    name: Eclipse Public License v1.0
    url: http://www.eclipse.org/legal/epl-v10.html
host: virtserver.swaggerhub.com
basePath: /skabashniuk/Che/1.0.0
schemes:
- https
paths:
  /service:
    get:
      summary: Searches CheService by list of ids
      description: Searches  CheService by list of ids, example ?id=io.typefox.theia-ide.che-service:1.2.3&org.eclipse.che.svn:4.2.3
      operationId: getServiceByIdList
      produces:
      - application/x-yaml
      - application/json
      parameters:
      - name: id
        in: query
        description: list if CheService ids.
        required: true
        type: array
        items:
          type: string
        collectionFormat: multi
      responses:
        200:
          description: The CheService successfully fetched
          schema:
            type: array
            items:
              $ref: '#/definitions/CheService'
        500:
          description: 500 Internal server error occurred
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Create a new CheService
      description: Create a new CheService
      operationId: addCheService
      consumes:
      - application/json
      - application/x-yaml
      produces:
      - application/json
      - application/x-yaml
      parameters:
      - in: body
        name: CheServiceItem
        description: CheFeature item to add
        required: false
        schema:
          $ref: '#/definitions/CheService'
      responses:
        201:
          description: The CheService successfully created
          schema:
            $ref: '#/definitions/CheService'
        400:
          description: 400 Server receives invalid input parameter
          schema:
            $ref: '#/definitions/Error'
        403:
          description: 403 The user does not have access to update resource
          schema:
            $ref: '#/definitions/Error'
        409:
          description: 409 Operation could not be performed because of conflict with prior state.
          schema:
            $ref: '#/definitions/Error'
  /service/{name}/{version}:
    get:
      summary: Get CheService by name and version
      description: Get CheService by name and version
      operationId: getServiceByNameAndVersion
      produces:
      - application/x-yaml
      - application/json
      parameters:
      - name: name
        in: path
        description: CheService name.
        required: true
        type: string
      - name: version
        in: path
        description: CheService version.
        required: true
        type: string
      responses:
        200:
          description: The CheService successfully fetched
          schema:
            $ref: '#/definitions/CheService'
        500:
          description: 500 Internal server error occurred
          schema:
            $ref: '#/definitions/Error'
    delete:
      summary: Removes CheService by name and version
      description: Removes CheService by name and version
      operationId: deleteServiceByNameAndVersion
      produces:
      - application/x-yaml
      - application/json
      parameters:
      - name: name
        in: path
        description: Service name.
        required: true
        type: string
      - name: version
        in: path
        description: Service version.
        required: true
        type: string
      responses:
        204:
          description: The CheService successfully removed
        403:
          description: 403 The user does not have access to update resource
          schema:
            $ref: '#/definitions/Error'
        404:
          description: 404 The specified resource was not found
          schema:
            $ref: '#/definitions/Error'
        500:
          description: 500 Internal server error occurred
          schema:
            $ref: '#/definitions/Error'
  /feature:
    get:
      summary: Searches CheFeature by list of ids
      description: Searches CheFeature by list of ids. For example, ?id=io.typefox.theia-ide.che-service:1.2.3&org.eclipse.che.svn:4.2
      operationId: searchFeatureByListOfId
      produces:
      - application/x-yaml
      - application/json
      parameters:
      - name: id
        in: query
        description: list if CheService ids.
        required: true
        type: array
        items:
          type: string
        collectionFormat: multi
      responses:
        200:
          description: The CheFeature successfully fetched
          schema:
            type: array
            items:
              $ref: '#/definitions/CheFeature'
        500:
          description: 500 Internal server error occurred
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Create a new CheFeature
      description: Create a new CheFeature
      operationId: addFeature
      consumes:
      - application/json
      - application/x-yaml
      produces:
      - application/json
      - application/x-yaml
      parameters:
      - in: body
        name: CheFeatureItem
        description: CheFeature item to add
        required: false
        schema:
          $ref: '#/definitions/CheFeature'
      responses:
        201:
          description: The CheFeature successfully created
          schema:
            $ref: '#/definitions/CheFeature'
        403:
          description: 403 The user does not have access to update resource
          schema:
            $ref: '#/definitions/Error'
        404:
          description: 404 The specified resource was not found
          schema:
            $ref: '#/definitions/Error'
        409:
          description: 409 Operation could not be performed because of conflict with prior state.
          schema:
            $ref: '#/definitions/Error'
        500:
          description: 500 Internal server error occurred
          schema:
            $ref: '#/definitions/Error'
  /feature/{name}/{version}:
    get:
      summary: Get CheFeature by name and version
      description: Get CheFeature by name and version
      operationId: searchFeatureByNameAndVersion
      produces:
      - application/x-yaml
      - application/json
      parameters:
      - name: name
        in: path
        description: CheFeature name.
        required: true
        type: string
      - name: version
        in: path
        description: CheFeature version.
        required: true
        type: string
      responses:
        200:
          description: The CheFeature successfully fetched
          schema:
            $ref: '#/definitions/CheFeature'
        500:
          description: 500 Internal server error occurred
          schema:
            $ref: '#/definitions/Error'
    delete:
      summary: Removes CheFeature by name and version
      description: Removes CheFeature by name and version
      operationId: deleteFeatureByNameAndVersion
      produces:
      - application/x-yaml
      - application/json
      parameters:
      - name: name
        in: path
        description: CheFeature name.
        required: true
        type: string
      - name: version
        in: path
        description: CheFeature version.
        required: true
        type: string
      responses:
        204:
          description: The CheFeature successfully removed
        403:
          description: 403 The user does not have access to update resource
          schema:
            $ref: '#/definitions/Error'
        404:
          description: 404 The specified resource was not found
          schema:
            $ref: '#/definitions/Error'
        409:
          description: 409 Operation could not be performed because of conflict with prior state.
          schema:
            $ref: '#/definitions/Error'
        500:
          description: 500 Internal server error occurred
          schema:
            $ref: '#/definitions/Error'
definitions:
  CheService:
    allOf:
    - $ref: '#/definitions/TypeMeta'
    - type: object
      required:
      - apiVersion
      - kind
      - metadata
      properties:
        apiVersion:
          type: string
          example: che.eclipse.org/v1
        kind:
          type: string
          example: CheService
        metadata:
          $ref: '#/definitions/ObjectMeta'
  CheServiceSpec:
    type: object
    required:
    - commands
    - pods
    - services
    - version
    properties:
      version:
        type: string
        example: 1.0.0
      services:
        type: array
        items:
          $ref: '#/definitions/Service'
      pods:
        type: array
        items:
          $ref: '#/definitions/Pod'
      commands:
        type: array
        items:
          $ref: '#/definitions/CheCommand'
  Pod:
    type: object
    description: Pod is a collection of containers that can run on a host. This resource is created by clients and scheduled onto hosts.
  Service:
    type: object
    description: Service is a named abstraction of software service (for example, mysql) consisting of local port (for example 3306) that the proxy listens on, and the selector that determines which pods will answer requests sent through the proxy.
  CheCommand:
    type: object
    required:
    - apiVersion
    - kind
    - metadata
    - spec
    properties:
      apiVersion:
        type: string
        example: che.eclipse.org/v1
      kind:
        type: string
        example: CheCommand
      metadata:
        $ref: '#/definitions/ObjectMeta'
      spec:
        $ref: '#/definitions/CheCommandSpec'
  CheCommandSpec:
    type: object
    required:
    - command
    - target-label-selector
    - working-dir
    properties:
      target-label-selector:
        type: string
        example: che.eclipse.org/container-name= theia-maven-sidecar
      working-dir:
        type: string
        example: $(project)
      command:
        type: array
        items:
          type: string
          example: mvn
  CheFeature:
    type: object
    required:
    - apiVersion
    - kind
    - metadata
    - spec
    properties:
      apiVersion:
        type: string
        example: che.eclipse.org/v1
      kind:
        type: string
        example: CheFeature
      metadata:
        $ref: '#/definitions/ObjectMeta'
      spec:
        $ref: '#/definitions/CheFeatureSpec'
    example:
      metadata:
        name: org.eclipse.che.theia.git
      apiVersion: che.eclipse.org/v1
      kind: CheFeature
      spec:
        services:
        - name: o.typefox.theia-ide.che-service.mainpod
          services:
          - name: THEIA_PLUGINS
            value: org.eclipse.che.terminal@latest
          - name: THEIA_PLUGINS
            value: org.eclipse.che.terminal@latest
          version: 51.233
        - name: o.typefox.theia-ide.che-service.mainpod
          services:
          - name: THEIA_PLUGINS
            value: org.eclipse.che.terminal@latest
          - name: THEIA_PLUGINS
            value: org.eclipse.che.terminal@latest
          version: 51.233
        version: 1.0.0
  CheFeatureSpec:
    type: object
    required:
    - services
    - version
    properties:
      version:
        type: string
        example: 1.0.0
      services:
        type: array
        items:
          $ref: '#/definitions/CheServiceReference'
    example:
      services:
      - name: o.typefox.theia-ide.che-service.mainpod
        services:
        - name: THEIA_PLUGINS
          value: org.eclipse.che.terminal@latest
        - name: THEIA_PLUGINS
          value: org.eclipse.che.terminal@latest
        version: 51.233
      - name: o.typefox.theia-ide.che-service.mainpod
        services:
        - name: THEIA_PLUGINS
          value: org.eclipse.che.terminal@latest
        - name: THEIA_PLUGINS
          value: org.eclipse.che.terminal@latest
        version: 51.233
      version: 1.0.0
  CheServiceReference:
    type: object
    required:
    - name
    - version
    properties:
      name:
        type: string
        example: o.typefox.theia-ide.che-service.mainpod
      version:
        type: string
        example: 51.233
      services:
        type: array
        items:
          $ref: '#/definitions/CheServiceParameter'
    example:
      name: o.typefox.theia-ide.che-service.mainpod
      services:
      - name: THEIA_PLUGINS
        value: org.eclipse.che.terminal@latest
      - name: THEIA_PLUGINS
        value: org.eclipse.che.terminal@latest
      version: 51.233
  CheServiceParameter:
    type: object
    required:
    - name
    - value
    properties:
      name:
        type: string
        example: THEIA_PLUGINS
      value:
        type: string
        example: org.eclipse.che.terminal@latest
    example:
      name: THEIA_PLUGINS
      value: org.eclipse.che.terminal@latest
  TypeMeta:
    type: object
    required:
    - apiVersion
    - kind
    properties:
      kind:
        type: string
        example: CheService
        description: Kind is a string value representing the REST resource this object represents.
      apiVersion:
        type: string
        example: che.eclipse.org/v1
        description: APIVersion defines the versioned schema of this representation of an object
    description: TypeMeta describes an individual object in an API response or request with strings representing the type of the object and its API schema version. Structures that are versioned or persisted should inline TypeMeta
  ObjectMeta:
    type: object
    required:
    - name
    properties:
      name:
        type: string
        example: org.eclipse.che.theia.git
        description: Object name. Name must be unique.
    example:
      name: org.eclipse.che.theia.git
  Error:
    type: object
    required:
    - message
    properties:
      message:
        type: string
responses:
  BadRequestException:
    description: 400 Server receives invalid input parameter
    schema:
      $ref: '#/definitions/Error'
  ForbiddenException:
    description: 403 The user does not have access to update resource
    schema:
      $ref: '#/definitions/Error'
  NotFoundException:
    description: 404 The specified resource was not found
    schema:
      $ref: '#/definitions/Error'
  ConflictException:
    description: 409 Operation could not be performed because of conflict with prior state.
    schema:
      $ref: '#/definitions/Error'
  ServerException:
    description: 500 Internal server error occurred
    schema:
      $ref: '#/definitions/Error'
